# Form implementation generated from reading ui file 'ui_files/main_design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.choosedata_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.choosedata_button.setObjectName("choosedata_button")
        self.verticalLayout_3.addWidget(self.choosedata_button)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.poly_degree_spinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.poly_degree_spinBox.setObjectName("poly_degree_spinBox")
        self.horizontalLayout_4.addWidget(self.poly_degree_spinBox)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.build_poly_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.build_poly_button.setObjectName("build_poly_button")
        self.verticalLayout_3.addWidget(self.build_poly_button)
        self.poly_display_textbrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.poly_display_textbrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.poly_display_textbrowser.setObjectName("poly_display_textbrowser")
        self.verticalLayout_3.addWidget(self.poly_display_textbrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.first_display_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.first_display_widget.setMinimumSize(QtCore.QSize(400, 300))
        self.first_display_widget.setMaximumSize(QtCore.QSize(400, 300))
        self.first_display_widget.setObjectName("first_display_widget")
        self.verticalLayout.addWidget(self.first_display_widget)
        self.second_display_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.second_display_widget.setMinimumSize(QtCore.QSize(400, 300))
        self.second_display_widget.setMaximumSize(QtCore.QSize(400, 300))
        self.second_display_widget.setObjectName("second_display_widget")
        self.verticalLayout.addWidget(self.second_display_widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choosedata_button.setText(_translate("MainWindow", "Выбрать файл с датой"))
        self.label.setText(_translate("MainWindow", "Выбор степени полинома"))
        self.build_poly_button.setText(_translate("MainWindow", "Построить полином заданной степени"))
